### PR TITLE
Update BlueToolFixup for macOS 15

### PR DESCRIPTION
**Pull request by vedantmgoyal9**

### CODE REVIEW

**Comment by tenglendon** [comment]
under MacOS 15 beta3 BlueToolFixup.kext can't load.
any solution ?

**Comment by adipierro** [comment]
@megabitzu could you please elaborate if it doesn't work with this PR or are you talking about release version?

**Comment by adipierro** [comment]
okay I've compiled BluetootFixup with a 'fix' from this PR, can confirm it works on 24A5331b

**Comment by adipierro** [comment]
but not after sleep :)
I will try to tinker with `pmheart-btf15-20240616` branch

**Comment by philsaino** [comment]
Hi, Same problem here on Sequoia... will be released a new version of the kext?

**Comment by FajleRabbi** [comment]
I'm also facing the same issue, is there any chances to release new version of the kext?

**Comment by fanpengy** [comment]
> > I'm also facing the same issue, is there any chances to release new version of the kext?
> 
> try this version [BlueToolFixup.kext.zip](https://github.com/user-attachments/files/17041987/BlueToolFixup.kext.zip) It's working for me

I'm curious where you got it from, it worked well for me, but it didn't apply any patches to /usr/sbin/bluetoothd, even thought it did work well for me.

**Comment by danyareshetnyak** [comment]
> I'm curious where you got it from, it worked well for me, but it didn't apply any patches to /usr/sbin/bluetoothd, even thought it did work well for me.

built from this [https://github.com/Lorys89/BrcmPatchRAM/](url)

**Comment by fanpengy** [comment]
> > I'm curious where you got it from, it worked well for me, but it didn't apply any patches to /usr/sbin/bluetoothd, even thought it did work well for me.
> 
> built from this [https://github.com/Lorys89/BrcmPatchRAM/](url)

Thanks ! ! !

**Comment by duluosheng** [comment]
bcm94352z lenovo version, does not work on macOS 15

**Comment by wwbfred** [comment]
> > I'm curious where you got it from, it worked well for me, but it didn't apply any patches to /usr/sbin/bluetoothd, even thought it did work well for me.
> 
> built from this [https://github.com/Lorys89/BrcmPatchRAM/](url)

I built from Lorys89's fork, but it doesn't work, and it's much smaller than your version.
By the way, your version of BlueToolFixup is the only one that works for me on the internet.

**Comment by MorfiMorfi** [comment]
I have a flash drive with Bluetooth version 2, unfortunately the file above did not help, maybe in my case some other edits are needed?

**Comment by lazosweb** [comment]
> > I'm also facing the same issue, is there any chances to release new version of the kext?
> 
> try this version [BlueToolFixup.kext.zip](https://github.com/user-attachments/files/17041987/BlueToolFixup.kext.zip) It's working for me

This worked for me for ASUS BT-400. What is the difference?

**Comment by luizmeliga** [comment]
I have a BT400 and the Bluetooth keeps searching and doesn't find any device. I've already tried using the BlueToolFixup.kext that they posted here, I also tried it with and without the NVRAM Patch. Does anyone know how to solve it? On Windows it works perfectly.

**Comment by vedantmgoyal9** [comment]
@zxystd can this be merged and hopefully, a new version of the kext can be released?

**Comment by lazosweb** [comment]
> I have a BT400 and the Bluetooth keeps searching and doesn't find any device. I've already tried using the BlueToolFixup.kext that they posted here, I also tried it with and without the NVRAM Patch. Does anyone know how to solve it? On Windows it works perfectly.

For me this (earching and doesn't find any device) happens when I use a USB that does not have a Broadcom chip.

**Comment by luizmeliga** [comment]
> > I have a BT400 and the Bluetooth keeps searching and doesn't find any device. I've already tried using the BlueToolFixup.kext that they posted here, I also tried it with and without the NVRAM Patch. Does anyone know how to solve it? On Windows it works perfectly.
> 
> For me this (searching and doesn't find any device) happens when I use a USB that does not have a Broadcom chip.

How do I find out his chip??

**Comment by PMheart** [comment]
@adipierro Does `pmheart-btf15-20240616` work for you after sleep?

**Comment by adipierro** [comment]
> @adipierro Does `pmheart-btf15-20240616` work for you after sleep?

Not really, since some beta version it actually makes `bluetoothd` crash frequently, and not work at all.

Bluetooth works, however, after sleep with this simple PR, if I turn Bluetooth off before suspending machine. And a quick fix is resetting `BluetoothExternalAdapterSomethingFailed` in nvram, and killing `bluetoothd` afterwards.

It might just not be able to "see" the adapter while USB is re-initializing, and could be my machine specific.

I tried to patch out the NVRAM option write in`bluetoothd` as well myself by analyzing it with ida, but unfortunately don't have enough reverse engineering experience for this.

Will it be useful I try to collect debug Bluetooth logs for you the moment it fails after sleep?

**Comment by PMheart** [comment]
Thanks for the heads up. Then for now I have no idea, apologies.

**Comment by Edwardwich** [comment]
> Thanks for the heads up. Then for now I have no idea, apologies.

bluetooth can't receive file after sleep its normal ?

**Comment by stevezhengshiqi** [comment]
@adipierro Hi, thank you for testing. There's a recent fix on BlueToolFixup if you can help to test. https://github.com/acidanthera/BrcmPatchRAM/actions/runs/11143115875

**Comment by adipierro** [comment]
@stevezhengshiqi thank you for letting me know about it 😊

I recently talked with PMheart about this patches in private, and I wanted to test them soon, but I still need to investigate bluetoothd crashes with it.

Although it mostly works with 15.1, there are still some issues after sleep. As soon as I find time for this I'd be happy to do it. Maybe even create new patches 👀

**Comment by tarkh** [comment]
> @adipierro Hi, thank you for testing. There's a recent fix on BlueToolFixup if you can help to test. [061486c](https://github.com/acidanthera/BrcmPatchRAM/commit/061486c9963b9a6c61760dc334d833d7156ea317) You can download the kext in https://github.com/acidanthera/BrcmPatchRAM/actions/runs/11143115875

Confirm BT works again on 15.0. Thank you!
```
BCM20702A0
Firmware Version:  v8718 c5810
Product ID:             0x180a
Vendor ID:              0x0b05  (ASUSTek Computer Inc.)
```

**Comment by ruler666** [comment]
And a quick fix is resetting `BluetoothExternalAdapterSomethingFailed` in nvram, and killing `bluetoothd` afterwards.

----------------------------------------------------------------------------------------------------------------------

Thank you so very very much for this! After million reboots, kexts, maps.....whatever....this worked. I didn't even know how to do it, so if anyone stumbles upon this thread, here's the drill:

sudo NVRAM bluetoothExternalDongleFailed=%00
sudo pkill bluetoothd

Before that with 'NVRAM -p' you can actually check what's going on and if you have %01 up there, most probably you have a problem you can fix with this.

**Pull request merged**
